### ISSUE TITLE
$XDG_DATA_HOME not defined on my Ubuntu 22.04 based Linux distribution

### ISSUE THREAD

**Issue by feldti** [GsDevKit/GsDevKit_stones#21]
I am jumping in the train ... so the first point is, that the installation is based on $XDG_DATA_HOME, which is not defined on my Ubuntu 22.04 based Linux distribution. So do not assume, that the variable has been set - and the Mac condition is also valid for Linux distributions

**Comment by dalehenrich** [comment]
GsDevKit_stones doesn't make that assumption. 

Here's the code in the [installation instructions](https://github.com/GsDevKit/GsDevKit_stones?tab=readme-ov-file#installation):
```
export STONES_DATA_HOME=$XDG_DATA_HOME
if [ "$STONES_DATA_HOME" = "" ] ; then
	# on Mac ensure the directory you choose exists
	export STONES_DATA_HOME=$HOME/.local/share
fi
```
GsDevKit_stones expects $STONES_DATA_HOME to be set ... Personally, I don't use $XDG_DATA_HOME for my registry, because I have a HOME directory that is shared across multiple hosts and I prefer to have a registry name space per host ...

If you find a place where $XDG_DATA_HOME is expected to be set, please submit a bug report or better yet submit pull request with a fix ...
